### ISSUE TITLE
Question: What is different between `replace` and `update` comment modes ?

### ISSUE THREAD

**Issue by mohanraj-r** [slavcodev/coverage-monitor-action#12]
@slavcodev Thanks for the cool comment mode feature! I have been looking for something that does this. It is not clear from the docs on how `replace` and `update` are different. Can you please explain?

Also I have had other code cov actions not work correctly on squash and merge - whey they are configured to run `on:` `push` event. Do you know if this action has been tested with such a scenario? Is there a way to run the action only on push events to a PR and not on merge to master ?

**Comment by slavcodev** [comment]
Hi.

Q1:
- `replace` mode removes existing comment and adds new at the end of comments if there are some, for example from users
- `update` mode tries to find existing and update it.

Q2: 
I'm afraid this action does not work with `push` event, since the payload for them is different, I don't recall which exactly but one of the key this action uses from  payload was missed in `push` event.

**Comment by mohanraj-r** [comment]
Thanks for the prompt response @slavcodev 

Q2: Can [pull_request event](https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request) be used then instead? Can't find doc on the different types -  e.g. would pushes to a PR trigger `edited` type event or any other event - so I can configure code cov only for pushes to a PR.

**Comment by slavcodev** [comment]
This action uses only `pull_request` event. I don't know any issues w/o squash and merge. Can you try and share the the result?

**Comment by mohanraj-r** [comment]
I can give that a try. Would `pull_request` event get triggered for pushes to the pull request ? I see the default actions are for `opened, synchronize, or reopened`.

[Events that trigger workflows - GitHub Help](https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request)
> Note: By default, a workflow only runs when a pull_request's activity type is opened, synchronize, or reopened. To trigger workflows for more activity types, use the types keyword.

**Comment by slavcodev** [comment]
No, AFAIU, `pull_request` event is not triggered on pushes.

**Comment by mohanraj-r** [comment]
How come there are multiple code cov reports on a PR then which necessitated the comment mode? Guess I am misunderstanding something.

**Comment by slavcodev** [comment]
Me too.

**Comment by mohanraj-r** [comment]
I used this action with `pull_request` event and have it working as expected on the pull request. 

```yml
on:
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize']
```

It is not triggered on squash and merge which works well for my use case.
