### ISSUE TITLE
Question: How do I get the code coverage badge in Readme with actual code coverage number

### ISSUE THREAD

**Issue by mohanraj-r** [slavcodev/coverage-monitor-action#13]
## Details

Currently I am using the badge provided by github workflow `<repo url>/workflows/Code%20coverage/badge.svg` where `Code%20coverage` is the name of the github action. It just displays the status as `passing`. 
I see that this github action posts a badge to PRs with actual code coverage percentage which has URL of the form `https://camo.githubusercontent.com/<some long hash>`. Wonder how I can use that badge in the repo Readme to reflect the current code cov % in master (or as of last merged PR).

**Comment by slavcodev** [comment]
It's not possible at the moment. That badge is generated runtime using the coverage percentage, to use it in readme, the badge or coverage report should be stored somewhere.

**Comment by mohanraj-r** [comment]
Ok, thanks for the clarification.
