### ISSUE TITLE
add v1 tag

### ISSUE THREAD

**Issue by rieschl** [slavcodev/coverage-monitor-action#25]
Many GitHub actions keep a generic, always up-to-date version tag for the major version, in that case `v1`.

That way, the workflow file doesn't have to be updated every time a new version is released. You can then just write:
```
uses: slavcodev/coverage-monitor-action@v1
```

For example the checkout action from GitHub: https://github.com/actions/checkout/releases/tag/v2

And every time you release a new version, you also overwrite the `v1` tag with the current release.

Thanks!

**Comment by slavcodev** [comment]
[Done](https://github.com/slavcodev/coverage-monitor-action/releases/tag/v1). Thank you for the suggestion.

**Comment by rieschl** [comment]
> 
> 
> [Done](https://github.com/slavcodev/coverage-monitor-action/releases/tag/v1). Thank you for the suggestion.

Thanks for the quick response!
