### ISSUE TITLE
Branch coverage is 0 in case no branches are present [bug]

### ISSUE THREAD

**Issue by judit-nahaj** [slavcodev/coverage-monitor-action#36]
## Details

When analyzing coverage on code that has no branches, branch coverage is 0.
Please see attached coverage report and screenshot of results.

## Context

In case there is a branch coverage percentage expected on a project, 0% can mean not reaching the thresholds, even though there is no uncovered branch in the code.

[clover_xml.txt](https://github.com/slavcodev/coverage-monitor-action/files/8009847/clover_xml.txt)
![2022-02-06_10h00_33](https://user-images.githubusercontent.com/14162187/152674774-3a5a9857-0ecd-4f94-a25a-e2a5e8f79e9f.png)

**Comment by slavcodev** [comment]
Thank you for report, I'll try to take a look asap.
