### ISSUE TITLE
[enhancement] PR is getting filthy with every commit

### ISSUE THREAD

**Issue by jmlavoier** [slavcodev/coverage-monitor-action#8]
**It's an enhancement suggestion.**

Every commit is creating the comment with the coverage, perfect it sucks some times, the PR is getting dirty and difficult to follow. 

## Details
It's an example of a dirty PR. 
![Screen Shot 2020-02-28 at 17 13 53](https://user-images.githubusercontent.com/3471145/75584206-ffdee200-5a4d-11ea-80d1-2817288395c2.png)

## Context
- A clear PR make things easier to reason about, follow, and review. 

## Possible implementation
My suggestion is to hide **last coverage comment** each commit pushed to PR, ie:
![Screen Shot 2020-02-28 at 17 21 01](https://user-images.githubusercontent.com/3471145/75584777-4ed94700-5a4f-11ea-8b9f-f09638f37cb3.png)

It's not a perfect solution, but it could be a good solution. If someone have a better idea let's discuss.

**Comment by slavcodev** [comment]
Thanks for the sugestion. I'm working on this problem, but haven't got a chance to finish it yet.
Also there is ther elated PR https://github.com/slavcodev/coverage-monitor-action/pull/6.
